version: "2"
services:
  web:
    image: nginx
    ports:
      - 80
  test:
    #build: ../
    image: infrataster
    volumes:
      - ./spec:/test/spec
    depends_on:
      - web
    network_mode: "service:web"
